spring:
  main:
    lazy-initialization: true

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:D:/springninja/course-db;DB_CLOSE_DELAY=10;AUTO_RECONNECT=TRUE;CIPHER=AES;DB_CLOSE_ON_EXIT=FALSE;
    #driverClassName: org.h2.Driver
    username: sa
    password: a b

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop #create-drop สร้าง schema ต่างๆที่เราได้ทำใน entity และจำ destroy schema เมื่อทำการปิด project #สร้าง schema แต่ไม่ destroy
    properties:
      hibernate.format_sql: false #ให้ format อยู่ในรูปที่อ่านง่ายขึ้น default = false
      hibernate.generate_statistics: false #วิเคราะได้ว่า query นี้ทำการเปิด ปิด connect เท่าไร จำนวนเวลา
      hibernate.query.immutable_entity_update_query_handling_mode: exception  #(warning | exception) default is warning
    open-in-view: false  #defalut คือ true jpa จะเปิด session เมื่ออยู่หน้า view

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 5KB
  http2:
    enabled: true
  undertow:
    accesslog:
      enabled: true # เขียน log เมื่อมีการยิง request เข้ามา
      dir: undertow-accesslog
      pattern: '%t %I %r %s %b %D'
